import "dotenv/config";
import type { Experience } from "../../../shared/src/types.js";
import { connectToDatabase } from "../lib/mongoose.js";
import { ExperienceModel } from "../models/index.js";

const DESTINATION_KEY = "lisbon-portugal";
const DESTINATION_CITY = "Lisbon";
const DESTINATION_COUNTRY = "Portugal";
const DESTINATION_COUNTRY_CODE = "PT";

type ExperienceSeed = Omit<Experience, "id">;

function point(label: string, coordinates: [number, number]) {
  return {
    type: "Point" as const,
    coordinates,
    label,
    city: DESTINATION_CITY,
    country: DESTINATION_COUNTRY,
    countryCode: DESTINATION_COUNTRY_CODE,
  };
}

function weeklyHours(opensAt: string, closesAt: string, closedDays: number[] = []) {
  return Array.from({ length: 7 }, (_, dayOfWeek) => ({
    dayOfWeek: dayOfWeek as 0 | 1 | 2 | 3 | 4 | 5 | 6,
    opensAt: closedDays.includes(dayOfWeek) ? undefined : opensAt,
    closesAt: closedDays.includes(dayOfWeek) ? undefined : closesAt,
    isClosed: closedDays.includes(dayOfWeek),
  }));
}

function buildExperience(seed: {
  slug: string;
  title: string;
  category: Experience["category"];
  coordinates: [number, number];
  summary: string;
  price: number;
  durationMinutes: number;
  tags: string[];
  openingHours: Experience["openingHours"];
  accessibility: Experience["accessibility"];
  supportedDietary?: Experience["supportedDietary"];
  preferredTransportModes: Experience["preferredTransportModes"];
  isActive?: boolean;
}): ExperienceSeed {
  return {
    slug: seed.slug,
    title: seed.title,
    category: seed.category,
    destinationKey: DESTINATION_KEY,
    location: point(seed.title, seed.coordinates),
    summary: seed.summary,
    price: {
      amount: seed.price,
      currency: "EUR",
    },
    durationMinutes: seed.durationMinutes,
    tags: seed.tags,
    openingHours: seed.openingHours,
    accessibility: seed.accessibility,
    supportedDietary: seed.supportedDietary ?? [],
    preferredTransportModes: seed.preferredTransportModes,
    isActive: seed.isActive ?? true,
  };
}

const museumAccessibility = {
  wheelchairAccessible: true,
  stepFree: true,
  lowVisionSupport: true,
  hearingSupport: true,
  mobilityLevel: "easy" as const,
};

const mixedAccessibility = {
  wheelchairAccessible: true,
  stepFree: true,
  lowVisionSupport: false,
  hearingSupport: false,
  mobilityLevel: "moderate" as const,
};

const demandingAccessibility = {
  wheelchairAccessible: false,
  stepFree: false,
  lowVisionSupport: false,
  hearingSupport: false,
  mobilityLevel: "demanding" as const,
};

const SEED_EXPERIENCES: ExperienceSeed[] = [
  buildExperience({
    slug: "belem-tower-visit",
    title: "Belem Tower Visit",
    category: "history",
    coordinates: [-9.2157, 38.6916],
    summary: "Iconic riverfront fort with compact historical exhibits.",
    price: 15,
    durationMinutes: 75,
    tags: ["history", "monument", "riverfront", "unesco"],
    openingHours: weeklyHours("10:00", "18:00", [1]),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["tram", "bus"].filter(Boolean) as Experience["preferredTransportModes"],
  }),
  buildExperience({
    slug: "jeronimos-monastery",
    title: "Jeronimos Monastery",
    category: "culture",
    coordinates: [-9.2066, 38.6979],
    summary: "Grand cloisters and Manueline architecture in Belem.",
    price: 18,
    durationMinutes: 120,
    tags: ["culture", "architecture", "unesco", "monastery"],
    openingHours: weeklyHours("09:30", "17:30", [1]),
    accessibility: museumAccessibility,
    preferredTransportModes: ["tram", "bus"].filter(Boolean) as Experience["preferredTransportModes"],
  }),
  buildExperience({
    slug: "maat-riverside-gallery",
    title: "MAAT Riverside Gallery",
    category: "culture",
    coordinates: [-9.1959, 38.6956],
    summary: "Contemporary art and design museum on the Tagus.",
    price: 11,
    durationMinutes: 105,
    tags: ["culture", "museum", "design", "riverfront"],
    openingHours: weeklyHours("10:00", "19:00", [1]),
    accessibility: museumAccessibility,
    preferredTransportModes: ["tram", "bike"],
  }),
  buildExperience({
    slug: "lx-factory-creative-walk",
    title: "LX Factory Creative Walk",
    category: "shopping",
    coordinates: [-9.1783, 38.7032],
    summary: "Independent shops, bookstores, studios, and murals.",
    price: 0,
    durationMinutes: 120,
    tags: ["shopping", "design", "street-art", "local-makers"],
    openingHours: weeklyHours("11:00", "20:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["tram", "bike", "walk"],
  }),
  buildExperience({
    slug: "timeout-market-lunch",
    title: "Time Out Market Lunch",
    category: "food",
    coordinates: [-9.1454, 38.7069],
    summary: "Large food hall with popular Lisbon chefs in one stop.",
    price: 22,
    durationMinutes: 90,
    tags: ["food", "market", "local", "indoor"],
    openingHours: weeklyHours("10:00", "23:00"),
    accessibility: museumAccessibility,
    supportedDietary: ["vegetarian", "vegan", "gluten-free", "pescatarian"],
    preferredTransportModes: ["walk", "metro", "tram"],
  }),
  buildExperience({
    slug: "alfama-fado-dinner",
    title: "Alfama Fado Dinner",
    category: "nightlife",
    coordinates: [-9.1291, 38.7112],
    summary: "Traditional fado supper in the old quarter.",
    price: 45,
    durationMinutes: 150,
    tags: ["nightlife", "music", "food", "alfama"],
    openingHours: weeklyHours("19:00", "23:30"),
    accessibility: mixedAccessibility,
    supportedDietary: ["vegetarian", "pescatarian"],
    preferredTransportModes: ["walk", "taxi"],
  }),
  buildExperience({
    slug: "sao-jorge-castle",
    title: "Sao Jorge Castle Ramparts",
    category: "history",
    coordinates: [-9.1335, 38.7139],
    summary: "Hilltop castle with panoramic views and archaeological remains.",
    price: 15,
    durationMinutes: 135,
    tags: ["history", "viewpoint", "castle", "stairs-only"],
    openingHours: weeklyHours("09:00", "21:00"),
    accessibility: demandingAccessibility,
    preferredTransportModes: ["walk", "taxi"],
  }),
  buildExperience({
    slug: "miradouro-santa-luzia",
    title: "Miradouro de Santa Luzia",
    category: "nature",
    coordinates: [-9.1295, 38.7114],
    summary: "Classic tiled terrace looking over Alfama rooftops.",
    price: 0,
    durationMinutes: 45,
    tags: ["nature", "viewpoint", "sunset", "photography"],
    openingHours: weeklyHours("07:00", "23:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk"],
  }),
  buildExperience({
    slug: "gulbenkian-museum",
    title: "Calouste Gulbenkian Museum",
    category: "culture",
    coordinates: [-9.1543, 38.7376],
    summary: "World-class art collection with quiet garden surroundings.",
    price: 14,
    durationMinutes: 120,
    tags: ["culture", "museum", "art", "garden"],
    openingHours: weeklyHours("10:00", "18:00", [1]),
    accessibility: museumAccessibility,
    preferredTransportModes: ["metro", "walk"],
  }),
  buildExperience({
    slug: "gulbenkian-gardens-stroll",
    title: "Gulbenkian Gardens Stroll",
    category: "wellness",
    coordinates: [-9.1536, 38.7381],
    summary: "Calm tree-lined paths for a quieter mid-day break.",
    price: 0,
    durationMinutes: 60,
    tags: ["wellness", "garden", "quiet", "nature"],
    openingHours: weeklyHours("08:00", "20:00"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["metro", "walk"],
  }),
  buildExperience({
    slug: "oceanario-lisbon",
    title: "Oceanario de Lisboa",
    category: "family",
    coordinates: [-9.0932, 38.7636],
    summary: "Large modern aquarium with immersive marine habitats.",
    price: 25,
    durationMinutes: 150,
    tags: ["family", "indoor", "marine-life", "education"],
    openingHours: weeklyHours("10:00", "20:00"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["metro", "taxi"],
  }),
  buildExperience({
    slug: "parque-das-nacoes-river-walk",
    title: "Parque das Nacoes River Walk",
    category: "nature",
    coordinates: [-9.0953, 38.7678],
    summary: "Flat modern promenade along the Tagus waterfront.",
    price: 0,
    durationMinutes: 75,
    tags: ["nature", "walk", "riverfront", "modern"],
    openingHours: weeklyHours("06:00", "23:00"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["walk", "bike", "metro"],
  }),
  buildExperience({
    slug: "national-tile-museum",
    title: "National Tile Museum",
    category: "history",
    coordinates: [-9.1137, 38.7237],
    summary: "Lisbon's azulejo story from sacred spaces to modern design.",
    price: 10,
    durationMinutes: 105,
    tags: ["history", "museum", "tiles", "culture"],
    openingHours: weeklyHours("10:00", "18:00", [1]),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["bus", "taxi"],
  }),
  buildExperience({
    slug: "graca-viewpoint-breakfast",
    title: "Graca Viewpoint Breakfast",
    category: "food",
    coordinates: [-9.1314, 38.7168],
    summary: "Scenic terrace breakfast above the old city.",
    price: 16,
    durationMinutes: 70,
    tags: ["food", "breakfast", "viewpoint", "local"],
    openingHours: weeklyHours("08:00", "12:00"),
    accessibility: mixedAccessibility,
    supportedDietary: ["vegetarian", "vegan", "gluten-free"],
    preferredTransportModes: ["walk", "tram"],
  }),
  buildExperience({
    slug: "chiado-bookshop-crawl",
    title: "Chiado Bookshop Crawl",
    category: "shopping",
    coordinates: [-9.1424, 38.7107],
    summary: "Independent bookshops and heritage literary stops.",
    price: 0,
    durationMinutes: 95,
    tags: ["shopping", "books", "culture", "walk"],
    openingHours: weeklyHours("10:00", "19:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "berardo-collection-preview",
    title: "Modern Collection Preview",
    category: "culture",
    coordinates: [-9.2058, 38.6973],
    summary: "Contemporary gallery stop in the Belem cluster.",
    price: 12,
    durationMinutes: 90,
    tags: ["culture", "museum", "modern-art", "indoor"],
    openingHours: weeklyHours("10:00", "18:30", [1]),
    accessibility: museumAccessibility,
    preferredTransportModes: ["tram", "bus"],
  }),
  buildExperience({
    slug: "belem-pasteis-stop",
    title: "Pasteis de Belem Tasting Stop",
    category: "food",
    coordinates: [-9.2039, 38.6971],
    summary: "Classic custard tart tasting near the monastery.",
    price: 8,
    durationMinutes: 35,
    tags: ["food", "dessert", "local", "quick-stop"],
    openingHours: weeklyHours("08:00", "22:00"),
    accessibility: museumAccessibility,
    supportedDietary: ["vegetarian"],
    preferredTransportModes: ["tram", "walk"],
  }),
  buildExperience({
    slug: "carmo-convent-ruins",
    title: "Carmo Convent Ruins",
    category: "history",
    coordinates: [-9.1408, 38.7127],
    summary: "Open-air Gothic ruins and small archaeological displays.",
    price: 7,
    durationMinutes: 75,
    tags: ["history", "ruins", "architecture", "museum"],
    openingHours: weeklyHours("10:00", "18:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "elevador-santa-justa",
    title: "Santa Justa Lift Ride",
    category: "adventure",
    coordinates: [-9.1394, 38.7122],
    summary: "Short vertical ride with a city panorama payoff.",
    price: 6,
    durationMinutes: 40,
    tags: ["adventure", "viewpoint", "architecture", "quick-stop"],
    openingHours: weeklyHours("09:00", "21:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk"],
  }),
  buildExperience({
    slug: "baixa-petiscos-crawl",
    title: "Baixa Petiscos Crawl",
    category: "food",
    coordinates: [-9.1378, 38.7108],
    summary: "Tapas-style tasting route through central Lisbon.",
    price: 28,
    durationMinutes: 120,
    tags: ["food", "tapas", "local", "night"],
    openingHours: weeklyHours("17:00", "23:00"),
    accessibility: museumAccessibility,
    supportedDietary: ["vegetarian", "pescatarian"],
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "principe-real-gardens",
    title: "Principe Real Gardens",
    category: "wellness",
    coordinates: [-9.1492, 38.7167],
    summary: "Shaded central park for a slower afternoon reset.",
    price: 0,
    durationMinutes: 55,
    tags: ["wellness", "park", "quiet", "shade"],
    openingHours: weeklyHours("07:00", "22:00"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "embaixada-design-shopping",
    title: "Embaixada Design Shopping",
    category: "shopping",
    coordinates: [-9.1497, 38.7161],
    summary: "Portuguese fashion and design brands inside a palace.",
    price: 0,
    durationMinutes: 80,
    tags: ["shopping", "design", "local-makers", "indoor"],
    openingHours: weeklyHours("12:00", "20:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "estufa-fria",
    title: "Estufa Fria Greenhouse",
    category: "nature",
    coordinates: [-9.1575, 38.7283],
    summary: "Lush greenhouse paths inside Eduardo VII park.",
    price: 4,
    durationMinutes: 70,
    tags: ["nature", "garden", "indoor-outdoor", "plants"],
    openingHours: weeklyHours("09:00", "17:30"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["metro", "walk"],
  }),
  buildExperience({
    slug: "eduardo-vii-park",
    title: "Eduardo VII Park Walk",
    category: "nature",
    coordinates: [-9.1548, 38.7286],
    summary: "Wide lawns and skyline views near Marques de Pombal.",
    price: 0,
    durationMinutes: 60,
    tags: ["nature", "park", "viewpoint", "walk"],
    openingHours: weeklyHours("06:00", "23:00"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "arroios-food-court",
    title: "Arroios Global Food Court",
    category: "food",
    coordinates: [-9.1332, 38.7312],
    summary: "Casual lunch stop with strong dietary coverage.",
    price: 15,
    durationMinutes: 75,
    tags: ["food", "casual", "vegetarian", "local"],
    openingHours: weeklyHours("11:30", "22:00"),
    accessibility: museumAccessibility,
    supportedDietary: ["vegetarian", "vegan", "halal", "gluten-free"],
    preferredTransportModes: ["metro", "walk"],
  }),
  buildExperience({
    slug: "campo-pequeno-concert",
    title: "Campo Pequeno Evening Concert",
    category: "nightlife",
    coordinates: [-9.1494, 38.7413],
    summary: "Indoor live performance venue in a historic arena.",
    price: 38,
    durationMinutes: 150,
    tags: ["nightlife", "music", "indoor", "evening"],
    openingHours: weeklyHours("19:30", "23:30"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["metro", "taxi"],
  }),
  buildExperience({
    slug: "azulejo-workshop",
    title: "Azulejo Painting Workshop",
    category: "culture",
    coordinates: [-9.142, 38.7164],
    summary: "Hands-on tile painting session with local artisans.",
    price: 32,
    durationMinutes: 120,
    tags: ["culture", "workshop", "tiles", "hands-on"],
    openingHours: weeklyHours("10:00", "18:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "docas-riverside-dinner",
    title: "Docas Riverside Dinner",
    category: "food",
    coordinates: [-9.1762, 38.6999],
    summary: "Marina-side dinner with an evening breeze.",
    price: 34,
    durationMinutes: 110,
    tags: ["food", "riverfront", "dinner", "sunset"],
    openingHours: weeklyHours("18:00", "23:30"),
    accessibility: museumAccessibility,
    supportedDietary: ["vegetarian", "pescatarian", "gluten-free"],
    preferredTransportModes: ["taxi", "bike", "tram"],
  }),
  buildExperience({
    slug: "cais-do-sodre-night-walk",
    title: "Cais do Sodre Night Walk",
    category: "nightlife",
    coordinates: [-9.1462, 38.7061],
    summary: "Music bars and busy streets near the river.",
    price: 0,
    durationMinutes: 90,
    tags: ["nightlife", "bars", "music", "walk"],
    openingHours: weeklyHours("20:00", "23:59"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "metro", "taxi"],
  }),
  buildExperience({
    slug: "rossio-square-photowalk",
    title: "Rossio Square Photo Walk",
    category: "culture",
    coordinates: [-9.1385, 38.714],
    summary: "Short guided route through iconic facades and paving patterns.",
    price: 12,
    durationMinutes: 60,
    tags: ["culture", "photography", "architecture", "walk"],
    openingHours: weeklyHours("08:00", "20:00"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["walk"],
  }),
  buildExperience({
    slug: "miradouro-senhora-do-monte",
    title: "Miradouro da Senhora do Monte",
    category: "nature",
    coordinates: [-9.1311, 38.7193],
    summary: "One of Lisbon's broadest skyline overlooks.",
    price: 0,
    durationMinutes: 50,
    tags: ["nature", "viewpoint", "sunrise", "hill"],
    openingHours: weeklyHours("06:30", "23:00"),
    accessibility: demandingAccessibility,
    preferredTransportModes: ["walk", "taxi"],
  }),
  buildExperience({
    slug: "feira-da-ladra-market",
    title: "Feira da Ladra Market Browse",
    category: "shopping",
    coordinates: [-9.1247, 38.7148],
    summary: "Tuesday and Saturday flea market for vintage finds.",
    price: 0,
    durationMinutes: 90,
    tags: ["shopping", "market", "vintage", "local"],
    openingHours: [
      { dayOfWeek: 0, isClosed: true },
      { dayOfWeek: 1, isClosed: true },
      { dayOfWeek: 2, opensAt: "09:00", closesAt: "17:00", isClosed: false },
      { dayOfWeek: 3, isClosed: true },
      { dayOfWeek: 4, isClosed: true },
      { dayOfWeek: 5, isClosed: true },
      { dayOfWeek: 6, opensAt: "09:00", closesAt: "17:00", isClosed: false },
    ],
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "tram"],
  }),
  buildExperience({
    slug: "museu-do-fado",
    title: "Museum of Fado",
    category: "history",
    coordinates: [-9.1277, 38.7125],
    summary: "Compact deep dive into Lisbon's signature sound.",
    price: 8,
    durationMinutes: 70,
    tags: ["history", "music", "museum", "alfama"],
    openingHours: weeklyHours("10:00", "18:00", [1]),
    accessibility: museumAccessibility,
    preferredTransportModes: ["walk", "tram"],
  }),
  buildExperience({
    slug: "botanical-garden-ajuda",
    title: "Ajuda Botanical Garden",
    category: "nature",
    coordinates: [-9.1993, 38.7094],
    summary: "Historic botanical garden with wide shaded routes.",
    price: 3,
    durationMinutes: 80,
    tags: ["nature", "garden", "quiet", "historic"],
    openingHours: weeklyHours("10:00", "17:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["bus", "taxi"],
  }),
  buildExperience({
    slug: "ajuda-palace",
    title: "National Palace of Ajuda",
    category: "history",
    coordinates: [-9.1984, 38.7073],
    summary: "Royal interiors and ceremonial halls in western Lisbon.",
    price: 15,
    durationMinutes: 105,
    tags: ["history", "palace", "interiors", "museum"],
    openingHours: weeklyHours("10:00", "18:00", [1]),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["bus", "taxi"],
  }),
  buildExperience({
    slug: "pink-street-evening",
    title: "Pink Street Evening",
    category: "nightlife",
    coordinates: [-9.1467, 38.7067],
    summary: "High-energy nightlife strip best for later hours.",
    price: 20,
    durationMinutes: 120,
    tags: ["nightlife", "bars", "music", "late"],
    openingHours: weeklyHours("21:00", "23:59"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "taxi"],
  }),
  buildExperience({
    slug: "lisbon-cooking-class",
    title: "Lisbon Cooking Class",
    category: "food",
    coordinates: [-9.1431, 38.7118],
    summary: "Interactive home-cooking lesson focused on seasonal dishes.",
    price: 55,
    durationMinutes: 180,
    tags: ["food", "workshop", "hands-on", "culture"],
    openingHours: weeklyHours("11:00", "20:00"),
    accessibility: museumAccessibility,
    supportedDietary: ["vegetarian", "vegan", "pescatarian"],
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "tram-28-scenic-ride",
    title: "Tram 28 Scenic Ride",
    category: "adventure",
    coordinates: [-9.1372, 38.7145],
    summary: "Classic tram line threading through Lisbon hills and landmarks.",
    price: 4,
    durationMinutes: 60,
    tags: ["adventure", "tram", "scenic", "classic"],
    openingHours: weeklyHours("07:00", "21:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["tram"],
  }),
  buildExperience({
    slug: "bairro-alto-rooftop",
    title: "Bairro Alto Rooftop Stop",
    category: "nightlife",
    coordinates: [-9.1453, 38.7131],
    summary: "Short sunset rooftop stop before the evening crowds.",
    price: 18,
    durationMinutes: 75,
    tags: ["nightlife", "sunset", "rooftop", "cocktails"],
    openingHours: weeklyHours("17:00", "23:00"),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "taxi"],
  }),
  buildExperience({
    slug: "chiado-modern-art-gallery",
    title: "Chiado Modern Art Gallery",
    category: "culture",
    coordinates: [-9.1432, 38.7095],
    summary: "Portuguese modern art in a central gallery space.",
    price: 9,
    durationMinutes: 80,
    tags: ["culture", "museum", "modern-art", "indoor"],
    openingHours: weeklyHours("10:00", "18:00", [1]),
    accessibility: museumAccessibility,
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "mercado-de-campo-de-ourique",
    title: "Campo de Ourique Market Dinner",
    category: "food",
    coordinates: [-9.1654, 38.7197],
    summary: "Neighborhood market hall with a calmer local dinner scene.",
    price: 24,
    durationMinutes: 95,
    tags: ["food", "market", "local", "indoor"],
    openingHours: weeklyHours("12:00", "23:00"),
    accessibility: museumAccessibility,
    supportedDietary: ["vegetarian", "vegan", "pescatarian", "gluten-free"],
    preferredTransportModes: ["bus", "taxi", "walk"],
  }),
  buildExperience({
    slug: "monsanto-forest-trail",
    title: "Monsanto Forest Urban Trail",
    category: "adventure",
    coordinates: [-9.1848, 38.7381],
    summary: "Urban forest route for travelers who want a bigger outdoor block.",
    price: 0,
    durationMinutes: 140,
    tags: ["adventure", "trail", "nature", "forest"],
    openingHours: weeklyHours("07:00", "20:00"),
    accessibility: demandingAccessibility,
    preferredTransportModes: ["bike", "taxi"],
  }),
  buildExperience({
    slug: "river-ferry-to-cacilhas",
    title: "River Ferry to Cacilhas",
    category: "adventure",
    coordinates: [-9.1476, 38.7056],
    summary: "Short Tagus crossing with broad water views.",
    price: 3,
    durationMinutes: 50,
    tags: ["adventure", "ferry", "riverfront", "scenic"],
    openingHours: weeklyHours("08:00", "22:00"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["ferry", "metro"],
  }),
  buildExperience({
    slug: "cacilhas-seafood-lunch",
    title: "Cacilhas Seafood Lunch",
    category: "food",
    coordinates: [-9.1495, 38.6868],
    summary: "Across-the-river lunch popular for grilled fish.",
    price: 30,
    durationMinutes: 100,
    tags: ["food", "seafood", "riverfront", "local"],
    openingHours: weeklyHours("12:00", "22:00"),
    accessibility: museumAccessibility,
    supportedDietary: ["pescatarian", "gluten-free"],
    preferredTransportModes: ["ferry", "walk"],
  }),
  buildExperience({
    slug: "miradouro-parque-eduardo-vii-sunrise",
    title: "Eduardo VII Sunrise View",
    category: "wellness",
    coordinates: [-9.1549, 38.7289],
    summary: "Light sunrise stop for travelers with early starts.",
    price: 0,
    durationMinutes: 35,
    tags: ["wellness", "sunrise", "viewpoint", "quiet"],
    openingHours: weeklyHours("06:00", "09:30"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["walk", "metro"],
  }),
  buildExperience({
    slug: "santos-design-district",
    title: "Santos Design District Walk",
    category: "shopping",
    coordinates: [-9.1572, 38.7068],
    summary: "Furniture showrooms and interiors boutiques along Santos.",
    price: 0,
    durationMinutes: 90,
    tags: ["shopping", "design", "interiors", "walk"],
    openingHours: weeklyHours("10:00", "19:00", [0]),
    accessibility: mixedAccessibility,
    preferredTransportModes: ["walk", "tram"],
  }),
  buildExperience({
    slug: "lisbon-wellness-spa",
    title: "Lisbon Wellness Spa Circuit",
    category: "wellness",
    coordinates: [-9.1487, 38.7229],
    summary: "Mid-trip recovery block with sauna and hydrotherapy.",
    price: 65,
    durationMinutes: 150,
    tags: ["wellness", "spa", "recovery", "indoor"],
    openingHours: weeklyHours("10:00", "21:00"),
    accessibility: museumAccessibility,
    preferredTransportModes: ["metro", "taxi"],
  }),
  buildExperience({
    slug: "family-tram-museum",
    title: "Carris Tram Museum",
    category: "family",
    coordinates: [-9.1774, 38.7037],
    summary: "Transit-focused museum that pairs well with riverfront stops.",
    price: 10,
    durationMinutes: 85,
    tags: ["family", "museum", "tram", "transport"],
    openingHours: weeklyHours("10:00", "18:00", [1]),
    accessibility: museumAccessibility,
    preferredTransportModes: ["tram", "bus"],
  }),
];

async function seedExperiences() {
  await connectToDatabase();

  await ExperienceModel.deleteMany({ destinationKey: DESTINATION_KEY });
  const documents = await ExperienceModel.insertMany(SEED_EXPERIENCES, { ordered: true });

  console.log(`Seeded ${documents.length} experiences for ${DESTINATION_KEY}.`);
}

seedExperiences()
  .catch((error) => {
    console.error("Failed to seed experiences.", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await ExperienceModel.db.close();
  });
